---

install:

  - if not exist C:\strawberry type nul > installperl.txt
  - if exist installperl.txt curl -O http://strawberryperl.com/download/5.24.0.1/strawberry-perl-5.24.0.1-64bit.msi
  - if exist installperl.txt msiexec /i strawberry-perl-5.24.0.1-64bit.msi /quiet /qn /norestart
  - if exist installperl.txt del strawberry-perl-5.24.0.1-64bit.msi
  - if exist installperl.txt del installperl.txt

  - if %ALIEN_INSTALL_TYPE% == system type nul > installmsys2.txt
  - if exist installmsys2.txt SET ALIEN_MSYS2_ROOT=c:\msys64
  - if exist installmsys2.txt del installmsys2.txt

  - SET PATH=C:\Perl5\bin;C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
  - PATH
  
  - perl -v
  - if not exist C:\Perl5 mkdir C:\Perl5
  - SET PERL5LIB=C:/Perl5/lib/perl5
  - SET PERL_LOCAL_LIB_ROOT=C:/Perl5
  - SET PERL_MB_OPT=--install_base C:/Perl5
  - SET PERL_MM_OPT=INSTALL_BASE=C:/Perl5
  - cpanm -n Dist::Zilla
  - dzil authordeps --missing | cpanm -n
  - cpanm -n Dist::Zilla::Plugin::Git::Check
  - dzil listdeps --missing | cpanm -n

build: off

test_script:
  - dzil test -v

cache:
  - C:\strawberry
  - C:\Perl5

shallow_clone: true

environment:
  matrix:
    - ALIEN_INSTALL_TYPE: system
    - ALIEN_INSTALL_TYPE: share
